<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Post;

/**
 * PostUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostUserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNbReads(Post $post)
    {
        $query = $this->createQueryBuilder('pu')
            ->select('sum(pu.nbReads)')
            ->where('pu.post = :post')
            ->setParameter('post', $post)
            ;
        return $query->getQuery()->getSingleScalarResult();
    }
}
